# Generated by Django 6.0.3 on 2026-03-08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multilingual_chat", "0004_message_is_bot_sender_nullable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="room_type",
            field=models.CharField(
                choices=[("ai", "AI"), ("direct", "Direct"), ("group", "Group")],
                default="direct",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="participants",
            field=models.ManyToManyField(blank=True, related_name="chat_rooms", to=settings.AUTH_USER_MODEL),
        ),
    ]
